// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BinlogMessageProto.proto

package org.dbsyncer.storage.binlog.proto;

public final class BinlogMessageProto {

    private BinlogMessageProto() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor internal_static_BinlogMessage_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_BinlogMessage_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_BinlogMap_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_BinlogMap_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_BinlogMap_RowEntry_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_BinlogMap_RowEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        String[] descriptorData = {"\n\030BinlogMessageProto.proto\"\\\n\rBinlogMess" + "age\022\026\n\016table_group_id\030\001 \001(\t\022\031\n\005event\030\002 \001"
                + "(\0162\n.EventEnum\022\030\n\004data\030\003 \001(\0132\n.BinlogMap" + "\"Y\n\tBinlogMap\022 \n\003row\030\001 \003(\0132\023.BinlogMap.R"
                + "owEntry\032*\n\010RowEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" + "e\030\002 \001(\014:\0028\001*/\n\tEventEnum\022\n\n\006UPDATE\020\000\022\n\n\006"
                + "INSERT\020\001\022\n\n\006DELETE\020\002B;\n!org.dbsyncer.sto" + "rage.binlog.protoB\022BinlogMessageProtoH\001P" + "\001b\006proto3"};
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[]{});
        internal_static_BinlogMessage_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_BinlogMessage_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_BinlogMessage_descriptor,
                new String[]{"TableGroupId", "Event", "Data",});
        internal_static_BinlogMap_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_BinlogMap_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_BinlogMap_descriptor, new String[]{"Row",});
        internal_static_BinlogMap_RowEntry_descriptor = internal_static_BinlogMap_descriptor.getNestedTypes().get(0);
        internal_static_BinlogMap_RowEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_BinlogMap_RowEntry_descriptor,
                new String[]{"Key", "Value",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
