// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BinlogMessageProto.proto

package org.dbsyncer.storage.binlog.proto;

/**
 * Protobuf type {@code Data}
 */
public final class Data extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Data)
        DataOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Data() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new Data();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private Data(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            row_ = com.google.protobuf.MapField.newMapField(
                                    RowDefaultEntryHolder.defaultEntry);
                            mutable_bitField0_ |= 0x00000001;
                        }
                        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
                                row__ = input.readMessage(
                                RowDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                        row_.getMutableMap().put(
                                row__.getKey(), row__.getValue());
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return org.dbsyncer.storage.binlog.proto.BinlogMessageProto.internal_static_Data_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
            int number) {
        switch (number) {
            case 1:
                return internalGetRow();
            default:
                throw new RuntimeException(
                        "Invalid map field number: " + number);
        }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return org.dbsyncer.storage.binlog.proto.BinlogMessageProto.internal_static_Data_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.dbsyncer.storage.binlog.proto.Data.class, org.dbsyncer.storage.binlog.proto.Data.Builder.class);
    }

    public static final int ROW_FIELD_NUMBER = 1;

    private static final class RowDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
                java.lang.String, com.google.protobuf.ByteString> defaultEntry =
                com.google.protobuf.MapEntry
                        .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                                org.dbsyncer.storage.binlog.proto.BinlogMessageProto.internal_static_Data_RowEntry_descriptor,
                                com.google.protobuf.WireFormat.FieldType.STRING,
                                "",
                                com.google.protobuf.WireFormat.FieldType.BYTES,
                                com.google.protobuf.ByteString.EMPTY);
    }

    private com.google.protobuf.MapField<
            java.lang.String, com.google.protobuf.ByteString> row_;

    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetRow() {
        if (row_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                    RowDefaultEntryHolder.defaultEntry);
        }
        return row_;
    }

    public int getRowCount() {
        return internalGetRow().getMap().size();
    }

    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */

    @java.lang.Override
    public boolean containsRow(
            java.lang.String key) {
        if (key == null) {
            throw new NullPointerException("map key");
        }
        return internalGetRow().getMap().containsKey(key);
    }

    /**
     * Use {@link #getRowMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getRow() {
        return getRowMap();
    }

    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getRowMap() {
        return internalGetRow().getMap();
    }

    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    @java.lang.Override

    public com.google.protobuf.ByteString getRowOrDefault(
            java.lang.String key,
            com.google.protobuf.ByteString defaultValue) {
        if (key == null) {
            throw new NullPointerException("map key");
        }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
                internalGetRow().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    @java.lang.Override

    public com.google.protobuf.ByteString getRowOrThrow(
            java.lang.String key) {
        if (key == null) {
            throw new NullPointerException("map key");
        }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
                internalGetRow().getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        com.google.protobuf.GeneratedMessageV3
                .serializeStringMapTo(
                        output,
                        internalGetRow(),
                        RowDefaultEntryHolder.defaultEntry,
                        1);
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
                : internalGetRow().getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
                    row__ = RowDefaultEntryHolder.defaultEntry.newBuilderForType()
                    .setKey(entry.getKey())
                    .setValue(entry.getValue())
                    .build();
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, row__);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof org.dbsyncer.storage.binlog.proto.Data)) {
            return super.equals(obj);
        }
        org.dbsyncer.storage.binlog.proto.Data other = (org.dbsyncer.storage.binlog.proto.Data) obj;

        if (!internalGetRow().equals(
                other.internalGetRow())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (!internalGetRow().getMap().isEmpty()) {
            hash = (37 * hash) + ROW_FIELD_NUMBER;
            hash = (53 * hash) + internalGetRow().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static org.dbsyncer.storage.binlog.proto.Data parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.dbsyncer.storage.binlog.proto.Data parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.dbsyncer.storage.binlog.proto.Data parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.dbsyncer.storage.binlog.proto.Data parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.dbsyncer.storage.binlog.proto.Data parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.dbsyncer.storage.binlog.proto.Data parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.dbsyncer.storage.binlog.proto.Data parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.dbsyncer.storage.binlog.proto.Data parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.dbsyncer.storage.binlog.proto.Data parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.dbsyncer.storage.binlog.proto.Data parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.dbsyncer.storage.binlog.proto.Data parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.dbsyncer.storage.binlog.proto.Data parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.dbsyncer.storage.binlog.proto.Data prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code Data}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Data)
            org.dbsyncer.storage.binlog.proto.DataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.dbsyncer.storage.binlog.proto.BinlogMessageProto.internal_static_Data_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 1:
                    return internalGetRow();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(
                int number) {
            switch (number) {
                case 1:
                    return internalGetMutableRow();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.dbsyncer.storage.binlog.proto.BinlogMessageProto.internal_static_Data_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.dbsyncer.storage.binlog.proto.Data.class, org.dbsyncer.storage.binlog.proto.Data.Builder.class);
        }

        // Construct using org.dbsyncer.storage.binlog.proto.Data.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            internalGetMutableRow().clear();
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return org.dbsyncer.storage.binlog.proto.BinlogMessageProto.internal_static_Data_descriptor;
        }

        @java.lang.Override
        public org.dbsyncer.storage.binlog.proto.Data getDefaultInstanceForType() {
            return org.dbsyncer.storage.binlog.proto.Data.getDefaultInstance();
        }

        @java.lang.Override
        public org.dbsyncer.storage.binlog.proto.Data build() {
            org.dbsyncer.storage.binlog.proto.Data result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public org.dbsyncer.storage.binlog.proto.Data buildPartial() {
            org.dbsyncer.storage.binlog.proto.Data result = new org.dbsyncer.storage.binlog.proto.Data(this);
            int from_bitField0_ = bitField0_;
            result.row_ = internalGetRow();
            result.row_.makeImmutable();
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof org.dbsyncer.storage.binlog.proto.Data) {
                return mergeFrom((org.dbsyncer.storage.binlog.proto.Data) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(org.dbsyncer.storage.binlog.proto.Data other) {
            if (other == org.dbsyncer.storage.binlog.proto.Data.getDefaultInstance()) return this;
            internalGetMutableRow().mergeFrom(
                    other.internalGetRow());
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            org.dbsyncer.storage.binlog.proto.Data parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (org.dbsyncer.storage.binlog.proto.Data) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private com.google.protobuf.MapField<
                java.lang.String, com.google.protobuf.ByteString> row_;

        private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
        internalGetRow() {
            if (row_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        RowDefaultEntryHolder.defaultEntry);
            }
            return row_;
        }

        private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
        internalGetMutableRow() {
            onChanged();
            ;
            if (row_ == null) {
                row_ = com.google.protobuf.MapField.newMapField(
                        RowDefaultEntryHolder.defaultEntry);
            }
            if (!row_.isMutable()) {
                row_ = row_.copy();
            }
            return row_;
        }

        public int getRowCount() {
            return internalGetRow().getMap().size();
        }

        /**
         * <code>map&lt;string, bytes&gt; row = 1;</code>
         */

        @java.lang.Override
        public boolean containsRow(
                java.lang.String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            return internalGetRow().getMap().containsKey(key);
        }

        /**
         * Use {@link #getRowMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getRow() {
            return getRowMap();
        }

        /**
         * <code>map&lt;string, bytes&gt; row = 1;</code>
         */
        @java.lang.Override

        public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getRowMap() {
            return internalGetRow().getMap();
        }

        /**
         * <code>map&lt;string, bytes&gt; row = 1;</code>
         */
        @java.lang.Override

        public com.google.protobuf.ByteString getRowOrDefault(
                java.lang.String key,
                com.google.protobuf.ByteString defaultValue) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
                    internalGetRow().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, bytes&gt; row = 1;</code>
         */
        @java.lang.Override

        public com.google.protobuf.ByteString getRowOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
                    internalGetRow().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public Builder clearRow() {
            internalGetMutableRow().getMutableMap()
                    .clear();
            return this;
        }

        /**
         * <code>map&lt;string, bytes&gt; row = 1;</code>
         */

        public Builder removeRow(
                java.lang.String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            internalGetMutableRow().getMutableMap()
                    .remove(key);
            return this;
        }

        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
        getMutableRow() {
            return internalGetMutableRow().getMutableMap();
        }

        /**
         * <code>map&lt;string, bytes&gt; row = 1;</code>
         */
        public Builder putRow(
                java.lang.String key,
                com.google.protobuf.ByteString value) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            if (value == null) {
                throw new NullPointerException("map value");
            }

            internalGetMutableRow().getMutableMap()
                    .put(key, value);
            return this;
        }

        /**
         * <code>map&lt;string, bytes&gt; row = 1;</code>
         */

        public Builder putAllRow(
                java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
            internalGetMutableRow().getMutableMap()
                    .putAll(values);
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Data)
    }

    // @@protoc_insertion_point(class_scope:Data)
    private static final org.dbsyncer.storage.binlog.proto.Data DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new org.dbsyncer.storage.binlog.proto.Data();
    }

    public static org.dbsyncer.storage.binlog.proto.Data getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
            PARSER = new com.google.protobuf.AbstractParser<Data>() {
        @java.lang.Override
        public Data parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Data(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<Data> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public org.dbsyncer.storage.binlog.proto.Data getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

