// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BinlogMessageProto.proto

package org.dbsyncer.storage.binlog.proto;

public interface DataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Data)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    int getRowCount();

    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    boolean containsRow(
            java.lang.String key);

    /**
     * Use {@link #getRowMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getRow();

    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getRowMap();

    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */

    /* nullable */
    com.google.protobuf.ByteString getRowOrDefault(
            java.lang.String key,
            /* nullable */
            com.google.protobuf.ByteString defaultValue);

    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */

    com.google.protobuf.ByteString getRowOrThrow(
            java.lang.String key);
}
