// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BinlogMessageProto.proto

package org.dbsyncer.storage.binlog.proto;

/**
 * Protobuf enum {@code EventEnum}
 */
public enum EventEnum implements com.google.protobuf.ProtocolMessageEnum {

    /**
     * <code>UPDATE = 0;</code>
     */
    UPDATE(0),
    /**
     * <code>INSERT = 1;</code>
     */
    INSERT(1),
    /**
     * <code>DELETE = 2;</code>
     */
    DELETE(2), UNRECOGNIZED(-1),;

    /**
     * <code>UPDATE = 0;</code>
     */
    public static final int UPDATE_VALUE = 0;
    /**
     * <code>INSERT = 1;</code>
     */
    public static final int INSERT_VALUE = 1;
    /**
     * <code>DELETE = 2;</code>
     */
    public static final int DELETE_VALUE = 2;

    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new IllegalArgumentException("Can't get the number of an unknown enum value.");
        }
        return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static EventEnum valueOf(int value) {
        return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EventEnum forNumber(int value) {
        switch (value) {
            case 0:
                return UPDATE;
            case 1:
                return INSERT;
            case 2:
                return DELETE;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventEnum> internalGetValueMap() {
        return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<EventEnum> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<EventEnum>() {

        public EventEnum findValueByNumber(int number) {
            return EventEnum.forNumber(number);
        }
    };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
        if (this == UNRECOGNIZED) {
            throw new IllegalStateException("Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
        return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
        return BinlogMessageProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventEnum[] VALUES = values();

    public static EventEnum valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
            throw new IllegalArgumentException("EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventEnum(int value) {
        this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EventEnum)
}
