CREATE TABLE `dbsyncer_cluster_node` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `CREATE_TIME` bigint NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` bigint NOT NULL COMMENT '修改时间',
  `NODE_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '节点ID，{ip}:{httpPort}',
  `NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '节点名称',
  `IP` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '节点 IP',
  `HTTP_PORT` int NOT NULL COMMENT 'HTTP 端口',
  `WORKER_ID` int NULL COMMENT '集群唯一ID(0~31)',
  `ROLE` tinyint NOT NULL DEFAULT 0 COMMENT '节点角色: 0-Follower, 1-Leader',
  `TERM` bigint NOT NULL DEFAULT 0 COMMENT '任期（单调递增，成为 Leader 时 +1，默认 0）',
  `HEARTBEAT_TIME` bigint NOT NULL DEFAULT 0 COMMENT '最后心跳毫秒',
  `START_TIME` bigint NOT NULL DEFAULT 0 COMMENT '节点启动时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `UK_NODE_ID` (`NODE_ID`) USING BTREE,
  UNIQUE KEY `UK_WORKER_ID` (`WORKER_ID`) USING BTREE,
  KEY `IDX_CLUSTER_HEARTBEAT` (`HEARTBEAT_TIME`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin COMMENT = '集群节点表' ROW_FORMAT = Dynamic;
