CREATE TABLE `dbsyncer_task` (
  `ID` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '唯一ID',
  `CREATE_TIME` bigint NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` bigint NOT NULL COMMENT '修改时间',
  `NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '任务名称',
  `TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '任务类型, 数据同步/订正校验/整库迁移',
  `JSON` mediumtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '配置信息',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `IDX_UPDATE_TIME` (`UPDATE_TIME`) USING BTREE,
  KEY `IDX_TYPE_UPDATE_TIME` (`TYPE`,`UPDATE_TIME`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '任务配置表' ROW_FORMAT = Dynamic;