CREATE TABLE `dbsyncer_cluster_node` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键，同时作为雪花 WorkerId（1–31）',
  `NODE_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '节点ID，{ip}:{httpPort}',
  `NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '展示名',
  `IP` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '节点 IP',
  `HTTP_PORT` int NOT NULL COMMENT 'HTTP 端口',
  `STATUS` tinyint NOT NULL DEFAULT 0 COMMENT '0-OFFLINE, 1-ONLINE',
  `LAST_HEARTBEAT_TIME` bigint NOT NULL DEFAULT 0 COMMENT '最后心跳毫秒',
  `START_TIME` bigint NOT NULL DEFAULT 0 COMMENT '进程启动时间',
  `CREATE_TIME` bigint NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` bigint NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `UK_CLUSTER_NODE` (`NODE_ID`) USING BTREE,
  KEY `IDX_CLUSTER_STATUS` (`STATUS`) USING BTREE,
  KEY `IDX_CLUSTER_HEARTBEAT` (`LAST_HEARTBEAT_TIME`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin COMMENT = '集群节点表' ROW_FORMAT = Dynamic;
