CREATE TABLE `dbsyncer_meta` (
  `ID` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '唯一ID',
  `NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '名称',
  `TYPE` varchar(24) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '配置类型(meta)',
  `STATE` int NOT NULL DEFAULT 0 COMMENT '任务状态',
  `TOTAL` bigint NOT NULL DEFAULT 0 COMMENT '处理数据总数',
  `META_SUCCESS` bigint NOT NULL DEFAULT 0 COMMENT '成功条数',
  `FAIL` bigint NOT NULL DEFAULT 0 COMMENT '失败条数',
  `CREATE_TIME` bigint(0) NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` bigint(0) NOT NULL COMMENT '修改时间',
  `JSON` mediumtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '快照/运行态等完整JSON内容',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_STATE_UPDATE_TIME`(`STATE`, `UPDATE_TIME`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '任务执行结果表' ROW_FORMAT = Dynamic;