CREATE TABLE `dbsyncer_user` (
  `ID` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '唯一ID',
  `CREATE_TIME` bigint NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` bigint NOT NULL COMMENT '修改时间',
  `USERNAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '账号',
  `PASSWORD` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '密码',
  `NICKNAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '昵称',
  `ROLE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '角色',
  `EMAIL` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '邮箱（多个使用逗号拼接）',
  `PHONE` varchar(11) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '手机号',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_TYPE_UPDATE_CREATE_TIME`(`TYPE`, `UPDATE_TIME`, `CREATE_TIME`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '用户配置表' ROW_FORMAT = Dynamic;