CREATE TABLE `dbsyncer_meta` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '唯一ID',
  `CREATE_TIME` bigint NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` bigint NOT NULL COMMENT '修改时间',
  `TASK_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '任务ID/任务明细ID',
  `STATE` tinyint NOT NULL DEFAULT 0 COMMENT '任务状态，0-未执行;1-运行中;2-停止中;3-已完成;',
  `IS_TASK_DETAIL` tinyint NOT NULL DEFAULT 1 COMMENT '是否任务明细, 0-否 1-是',
  `TOTAL` bigint NOT NULL DEFAULT 0 COMMENT '总数',
  `SUCCESS` bigint NOT NULL DEFAULT 0 COMMENT '成功数',
  `FAIL` bigint NOT NULL DEFAULT 0 COMMENT '失败数',
  `DIFF` bigint NOT NULL DEFAULT 0 COMMENT '差异数',
  `FIXED` bigint NOT NULL DEFAULT 0 COMMENT '订正数',
  `SNAPSHOT` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '快照信息',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `IDX_TASK_UPDATE_TIME_FAIL` (`TASK_ID`, `FAIL`, `UPDATE_TIME`) USING BTREE,
  KEY `IDX_TASK_DETAIL_STATE` (`IS_TASK_DETAIL`, `STATE`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin COMMENT = '任务执行结果表' ROW_FORMAT = Dynamic;
