# \u670D\u52A1IP
server.ip=127.0.0.1
# \u8BBF\u95EE\u7AEF\u53E3
server.port=18686

# \u542F\u7528SSL\u914D\u7F6E(false-\u5173\u95ED; true-\u5F00\u542F)
server.ssl.enabled=false
# \u6307\u5B9A\u5916\u90E8\u914D\u7F6E\u6587\u4EF6
server.ssl.key-store=conf/dbsyncer.p12
server.ssl.key-store-password=dbsyncer
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=dbsyncer

# \u542F\u7528http\u7AEF\u53E3(false-\u5173\u95ED; true-\u5F00\u542F)
server.http.enabled=false
# server.ssl.enabled\u548Cserver.http.enabled\u540C\u65F6\u5F00\u542F\u751F\u6548
server.http.port=8080
# \u5F3A\u5236http\u91CD\u5B9A\u5411https\u7AEF\u53E3(false-\u5173\u95ED; true-\u5F00\u542F)
server.http.redirect=false

# \u4F1A\u8BDD\u8FC7\u671F\u65F6\u95F4(\u79D2)
server.servlet.session.timeout=1800
# \u8BBF\u95EE\u670D\u52A1\u7684\u8DEF\u5F84\uFF0C\u2018/\u2019 -> http://${server.ip}:${server.port}/
server.servlet.context-path=/
spring.profiles.active=default
#All < Trace < Debug < Info < Warn < Error < Fatal < OFF
logging.level.root=info

#web
# \u673A\u5668\u7684\u552F\u4E00\u7F16\u53F7\uFF08\u5355\u673A\u90E8\u7F72\u5219\u586B\u9ED8\u8BA4\u503C; \u90E8\u7F72\u96C6\u7FA4\u65F6, \u8981\u4FDD\u8BC1\u7F16\u53F7\u5728\u96C6\u7FA4\u4E2D\u552F\u4E00\uFF09
dbsyncer.web.worker.id=1
# \u5B9A\u65F6\u4EFB\u52A1\u7EBF\u7A0B\u6570
dbsyncer.web.scheduler.pool-size=8
# \u91CD\u7F6Eadmin\u9ED8\u8BA4\u5BC6\u7801\uFF08false-\u7981\u7528; true-\u91CD\u7F6E, \u9AD8\u5371\u64CD\u4F5C, \u6062\u590D\u540E\u4E00\u5B9A\u8981\u6539\u56DEfalse\uFF09
dbsyncer.web.security.reset-pwd=false

#common
# \u8C03\u5EA6\u7EBF\u7A0B\u6570
dbsyncer.common.dispatch.thread-core-size=8
# \u8C03\u5EA6\u6700\u5927\u7EBF\u7A0B\u6570
dbsyncer.common.dispatch.max-thread-size=16
# \u8C03\u5EA6\u7EBF\u7A0B\u6C60\u961F\u5217
dbsyncer.common.dispatch.thread-queue-capacity=64

#parser
# *********************** \u901A\u7528\u6267\u884C\u5668\u914D\u7F6E ***********************
# [GeneralBufferActuator]\u7EBF\u7A0B\u6570
dbsyncer.parser.general.thread-core-size=8
# [GeneralBufferActuator]\u6700\u5927\u7EBF\u7A0B\u6570
dbsyncer.parser.general.max-thread-size=16
# [GeneralBufferActuator]\u7EBF\u7A0B\u6C60\u961F\u5217
dbsyncer.parser.general.thread-queue-capacity=64
# [GeneralBufferActuator]\u5355\u6B21\u6267\u884C\u4EFB\u52A1\u6570
dbsyncer.parser.general.buffer-writer-count=1000
# [GeneralBufferActuator]\u6BCF\u6B21\u6D88\u8D39\u7F13\u5B58\u961F\u5217\u7684\u4EFB\u52A1\u6570
dbsyncer.parser.general.buffer-pull-count=20000
# [GeneralBufferActuator]\u7F13\u5B58\u961F\u5217\u5BB9\u91CF
dbsyncer.parser.general.buffer-queue-capacity=50000
# [GeneralBufferActuator]\u5B9A\u65F6\u6D88\u8D39\u7F13\u5B58\u961F\u5217\u95F4\u9694(\u6BEB\u79D2)
dbsyncer.parser.general.buffer-period-millisecond=300
# *********************** \u8868\u6267\u884C\u5668\u914D\u7F6E ***********************
# [TableGroupBufferActuator]\u7EBF\u7A0B\u6570
dbsyncer.parser.table.group.thread-core-size=1
# [TableGroupBufferActuator]\u6700\u5927\u7EBF\u7A0B\u6570
dbsyncer.parser.table.group.max-thread-size=1
# [TableGroupBufferActuator]\u7EBF\u7A0B\u6C60\u961F\u5217
dbsyncer.parser.table.group.thread-queue-capacity=16
# [TableGroupBufferActuator]\u5355\u6B21\u6267\u884C\u4EFB\u52A1\u6570
dbsyncer.parser.table.group.buffer-writer-count=1000
# [TableGroupBufferActuator]\u6BCF\u6B21\u6D88\u8D39\u7F13\u5B58\u961F\u5217\u7684\u4EFB\u52A1\u6570
dbsyncer.parser.table.group.buffer-pull-count=1000
# [TableGroupBufferActuator]\u7F13\u5B58\u961F\u5217\u5BB9\u91CF
dbsyncer.parser.table.group.buffer-queue-capacity=10000
# [TableGroupBufferActuator]\u5B9A\u65F6\u6D88\u8D39\u7F13\u5B58\u961F\u5217\u95F4\u9694(\u6BEB\u79D2)
dbsyncer.parser.table.group.buffer-period-millisecond=300

#storage
# \u6570\u636E\u5B58\u50A8\u7C7B\u578B:h2(\u9ED8\u8BA4)/disk(\u4E0D\u63A8\u8350)/mysql(\u63A8\u8350\u751F\u4EA7\u73AF\u5883\u4F7F\u7528)
#dbsyncer.storage.type=h2
#dbsyncer.storage.h2.url=jdbc:h2:file:./data/dbsyncer;MODE=MySQL;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=0;TRACE_LEVEL_SYSTEM_OUT=0
#dbsyncer.storage.h2.username=sa
# \u751F\u4EA7\u82E5\u9700\u52A0\u5BC6\uFF0C\u53EF\u5728\u9996\u6B21\u90E8\u7F72\u65F6\u5C31\u8BBE\u597D\uFF0C\u9700\u5728\u7B2C\u4E00\u6B21\u521B\u5EFA\u5E93\u6587\u4EF6\u4E4B\u524D\u914D\u7F6E\u597D\uFF08\u6216\u5220\u6389\u65E7\u5E93\u540E\u91CD\u542F\uFF09\u3002
#dbsyncer.storage.h2.password=
dbsyncer.storage.mysql.url=jdbc:mysql://127.0.0.1:3306/dbsyncer?rewriteBatchedStatements=true&seUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false&verifyServerCertificate=false&autoReconnect=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true
dbsyncer.storage.mysql.username=root
dbsyncer.storage.mysql.password=123456
# [StorageBufferActuator]\u7EBF\u7A0B\u6570
dbsyncer.storage.thread-core-size=4
# [StorageBufferActuator]\u6700\u5927\u7EBF\u7A0B\u6570
dbsyncer.storage.max-thread-size=8
# [StorageBufferActuator]\u7EBF\u7A0B\u6C60\u961F\u5217
dbsyncer.storage.thread-queue-capacity=64
# [StorageBufferActuator]\u5355\u6B21\u6267\u884C\u4EFB\u52A1\u6570
dbsyncer.storage.buffer-writer-count=1000
# [StorageBufferActuator]\u6BCF\u6B21\u6D88\u8D39\u7F13\u5B58\u961F\u5217\u7684\u4EFB\u52A1\u6570
dbsyncer.storage.buffer-pull-count=20000
# [StorageBufferActuator]\u7F13\u5B58\u961F\u5217\u5BB9\u91CF
dbsyncer.storage.buffer-queue-capacity=50000
# [StorageBufferActuator]\u5B9A\u65F6\u6D88\u8D39\u7F13\u5B58\u961F\u5217\u95F4\u9694(\u6BEB\u79D2)
dbsyncer.storage.buffer-period-millisecond=300