-- MySQL测试数据

-- 源表
CREATE TABLE ddlTestUserInfo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 目标表 (从源表同步)
CREATE TABLE ddlTestUserInfo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- MySQL到MySQL的DDL测试语句

-- ADD COLUMN
ALTER TABLE ddlTestUserInfo ADD COLUMN phone VARCHAR(20) AFTER email;

-- DROP COLUMN
ALTER TABLE ddlTestUserInfo DROP COLUMN email;

-- MODIFY COLUMN
ALTER TABLE ddlTestUserInfo MODIFY COLUMN username VARCHAR(100) NOT NULL;

-- CHANGE COLUMN (重命名字段)
ALTER TABLE ddlTestUserInfo CHANGE COLUMN username user_name VARCHAR(50);