// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BinlogMessageProto.proto

package org.dbsyncer.common.binlog.proto;

/**
 * Protobuf type {@code BinlogMessage}
 */
public final class BinlogMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BinlogMessage)
    BinlogMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BinlogMessage.newBuilder() to construct.
  private BinlogMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BinlogMessage() {
    tableGroupId_ = "";
    event_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BinlogMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.dbsyncer.common.binlog.proto.BinlogMessageProto.internal_static_BinlogMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.dbsyncer.common.binlog.proto.BinlogMessageProto.internal_static_BinlogMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.dbsyncer.common.binlog.proto.BinlogMessage.class, org.dbsyncer.common.binlog.proto.BinlogMessage.Builder.class);
  }

  public static final int TABLE_GROUP_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tableGroupId_ = "";
  /**
   * <code>string table_group_id = 1;</code>
   * @return The tableGroupId.
   */
  @java.lang.Override
  public java.lang.String getTableGroupId() {
    java.lang.Object ref = tableGroupId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableGroupId_ = s;
      return s;
    }
  }
  /**
   * <code>string table_group_id = 1;</code>
   * @return The bytes for tableGroupId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableGroupIdBytes() {
    java.lang.Object ref = tableGroupId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableGroupId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_FIELD_NUMBER = 2;
  private int event_ = 0;
  /**
   * <code>.EventEnum event = 2;</code>
   * @return The enum numeric value on the wire for event.
   */
  @java.lang.Override public int getEventValue() {
    return event_;
  }
  /**
   * <code>.EventEnum event = 2;</code>
   * @return The event.
   */
  @java.lang.Override public org.dbsyncer.common.binlog.proto.EventEnum getEvent() {
    org.dbsyncer.common.binlog.proto.EventEnum result = org.dbsyncer.common.binlog.proto.EventEnum.forNumber(event_);
    return result == null ? org.dbsyncer.common.binlog.proto.EventEnum.UNRECOGNIZED : result;
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private org.dbsyncer.common.binlog.proto.BinlogMap data_;
  /**
   * <code>.BinlogMap data = 3;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.BinlogMap data = 3;</code>
   * @return The data.
   */
  @java.lang.Override
  public org.dbsyncer.common.binlog.proto.BinlogMap getData() {
    return data_ == null ? org.dbsyncer.common.binlog.proto.BinlogMap.getDefaultInstance() : data_;
  }
  /**
   * <code>.BinlogMap data = 3;</code>
   */
  @java.lang.Override
  public org.dbsyncer.common.binlog.proto.BinlogMapOrBuilder getDataOrBuilder() {
    return data_ == null ? org.dbsyncer.common.binlog.proto.BinlogMap.getDefaultInstance() : data_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableGroupId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tableGroupId_);
    }
    if (event_ != org.dbsyncer.common.binlog.proto.EventEnum.UPDATE.getNumber()) {
      output.writeEnum(2, event_);
    }
    if (data_ != null) {
      output.writeMessage(3, getData());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableGroupId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tableGroupId_);
    }
    if (event_ != org.dbsyncer.common.binlog.proto.EventEnum.UPDATE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, event_);
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getData());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.dbsyncer.common.binlog.proto.BinlogMessage)) {
      return super.equals(obj);
    }
    org.dbsyncer.common.binlog.proto.BinlogMessage other = (org.dbsyncer.common.binlog.proto.BinlogMessage) obj;

    if (!getTableGroupId()
        .equals(other.getTableGroupId())) return false;
    if (event_ != other.event_) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TABLE_GROUP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTableGroupId().hashCode();
    hash = (37 * hash) + EVENT_FIELD_NUMBER;
    hash = (53 * hash) + event_;
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.dbsyncer.common.binlog.proto.BinlogMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.dbsyncer.common.binlog.proto.BinlogMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BinlogMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BinlogMessage)
      org.dbsyncer.common.binlog.proto.BinlogMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dbsyncer.common.binlog.proto.BinlogMessageProto.internal_static_BinlogMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dbsyncer.common.binlog.proto.BinlogMessageProto.internal_static_BinlogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.dbsyncer.common.binlog.proto.BinlogMessage.class, org.dbsyncer.common.binlog.proto.BinlogMessage.Builder.class);
    }

    // Construct using org.dbsyncer.common.binlog.proto.BinlogMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tableGroupId_ = "";
      event_ = 0;
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.dbsyncer.common.binlog.proto.BinlogMessageProto.internal_static_BinlogMessage_descriptor;
    }

    @java.lang.Override
    public org.dbsyncer.common.binlog.proto.BinlogMessage getDefaultInstanceForType() {
      return org.dbsyncer.common.binlog.proto.BinlogMessage.getDefaultInstance();
    }

    @java.lang.Override
    public org.dbsyncer.common.binlog.proto.BinlogMessage build() {
      org.dbsyncer.common.binlog.proto.BinlogMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.dbsyncer.common.binlog.proto.BinlogMessage buildPartial() {
      org.dbsyncer.common.binlog.proto.BinlogMessage result = new org.dbsyncer.common.binlog.proto.BinlogMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.dbsyncer.common.binlog.proto.BinlogMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tableGroupId_ = tableGroupId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.event_ = event_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.data_ = dataBuilder_ == null
            ? data_
            : dataBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.dbsyncer.common.binlog.proto.BinlogMessage) {
        return mergeFrom((org.dbsyncer.common.binlog.proto.BinlogMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.dbsyncer.common.binlog.proto.BinlogMessage other) {
      if (other == org.dbsyncer.common.binlog.proto.BinlogMessage.getDefaultInstance()) return this;
      if (!other.getTableGroupId().isEmpty()) {
        tableGroupId_ = other.tableGroupId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.event_ != 0) {
        setEventValue(other.getEventValue());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tableGroupId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              event_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tableGroupId_ = "";
    /**
     * <code>string table_group_id = 1;</code>
     * @return The tableGroupId.
     */
    public java.lang.String getTableGroupId() {
      java.lang.Object ref = tableGroupId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableGroupId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string table_group_id = 1;</code>
     * @return The bytes for tableGroupId.
     */
    public com.google.protobuf.ByteString
        getTableGroupIdBytes() {
      java.lang.Object ref = tableGroupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableGroupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string table_group_id = 1;</code>
     * @param value The tableGroupId to set.
     * @return This builder for chaining.
     */
    public Builder setTableGroupId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tableGroupId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string table_group_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableGroupId() {
      tableGroupId_ = getDefaultInstance().getTableGroupId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string table_group_id = 1;</code>
     * @param value The bytes for tableGroupId to set.
     * @return This builder for chaining.
     */
    public Builder setTableGroupIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tableGroupId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int event_ = 0;
    /**
     * <code>.EventEnum event = 2;</code>
     * @return The enum numeric value on the wire for event.
     */
    @java.lang.Override public int getEventValue() {
      return event_;
    }
    /**
     * <code>.EventEnum event = 2;</code>
     * @param value The enum numeric value on the wire for event to set.
     * @return This builder for chaining.
     */
    public Builder setEventValue(int value) {
      event_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.EventEnum event = 2;</code>
     * @return The event.
     */
    @java.lang.Override
    public org.dbsyncer.common.binlog.proto.EventEnum getEvent() {
      org.dbsyncer.common.binlog.proto.EventEnum result = org.dbsyncer.common.binlog.proto.EventEnum.forNumber(event_);
      return result == null ? org.dbsyncer.common.binlog.proto.EventEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.EventEnum event = 2;</code>
     * @param value The event to set.
     * @return This builder for chaining.
     */
    public Builder setEvent(org.dbsyncer.common.binlog.proto.EventEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      event_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.EventEnum event = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEvent() {
      bitField0_ = (bitField0_ & ~0x00000002);
      event_ = 0;
      onChanged();
      return this;
    }

    private org.dbsyncer.common.binlog.proto.BinlogMap data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.dbsyncer.common.binlog.proto.BinlogMap, org.dbsyncer.common.binlog.proto.BinlogMap.Builder, org.dbsyncer.common.binlog.proto.BinlogMapOrBuilder> dataBuilder_;
    /**
     * <code>.BinlogMap data = 3;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.BinlogMap data = 3;</code>
     * @return The data.
     */
    public org.dbsyncer.common.binlog.proto.BinlogMap getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? org.dbsyncer.common.binlog.proto.BinlogMap.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.BinlogMap data = 3;</code>
     */
    public Builder setData(org.dbsyncer.common.binlog.proto.BinlogMap value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
      } else {
        dataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.BinlogMap data = 3;</code>
     */
    public Builder setData(
        org.dbsyncer.common.binlog.proto.BinlogMap.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.BinlogMap data = 3;</code>
     */
    public Builder mergeData(org.dbsyncer.common.binlog.proto.BinlogMap value) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          data_ != null &&
          data_ != org.dbsyncer.common.binlog.proto.BinlogMap.getDefaultInstance()) {
          getDataBuilder().mergeFrom(value);
        } else {
          data_ = value;
        }
      } else {
        dataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.BinlogMap data = 3;</code>
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000004);
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.BinlogMap data = 3;</code>
     */
    public org.dbsyncer.common.binlog.proto.BinlogMap.Builder getDataBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.BinlogMap data = 3;</code>
     */
    public org.dbsyncer.common.binlog.proto.BinlogMapOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            org.dbsyncer.common.binlog.proto.BinlogMap.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.BinlogMap data = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.dbsyncer.common.binlog.proto.BinlogMap, org.dbsyncer.common.binlog.proto.BinlogMap.Builder, org.dbsyncer.common.binlog.proto.BinlogMapOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.dbsyncer.common.binlog.proto.BinlogMap, org.dbsyncer.common.binlog.proto.BinlogMap.Builder, org.dbsyncer.common.binlog.proto.BinlogMapOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BinlogMessage)
  }

  // @@protoc_insertion_point(class_scope:BinlogMessage)
  private static final org.dbsyncer.common.binlog.proto.BinlogMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.dbsyncer.common.binlog.proto.BinlogMessage();
  }

  public static org.dbsyncer.common.binlog.proto.BinlogMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BinlogMessage>
      PARSER = new com.google.protobuf.AbstractParser<BinlogMessage>() {
    @java.lang.Override
    public BinlogMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BinlogMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BinlogMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.dbsyncer.common.binlog.proto.BinlogMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

