// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BinlogMessageProto.proto

package org.dbsyncer.common.binlog.proto;

/**
 * Protobuf type {@code BinlogMap}
 */
public final class BinlogMap extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BinlogMap)
    BinlogMapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BinlogMap.newBuilder() to construct.
  private BinlogMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BinlogMap() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BinlogMap();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.dbsyncer.common.binlog.proto.BinlogMessageProto.internal_static_BinlogMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetRow();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.dbsyncer.common.binlog.proto.BinlogMessageProto.internal_static_BinlogMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.dbsyncer.common.binlog.proto.BinlogMap.class, org.dbsyncer.common.binlog.proto.BinlogMap.Builder.class);
  }

  public static final int ROW_FIELD_NUMBER = 1;
  private static final class RowDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.ByteString> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                org.dbsyncer.common.binlog.proto.BinlogMessageProto.internal_static_BinlogMap_RowEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BYTES,
                com.google.protobuf.ByteString.EMPTY);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.ByteString> row_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
  internalGetRow() {
    if (row_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          RowDefaultEntryHolder.defaultEntry);
    }
    return row_;
  }
  public int getRowCount() {
    return internalGetRow().getMap().size();
  }
  /**
   * <code>map&lt;string, bytes&gt; row = 1;</code>
   */
  @java.lang.Override
  public boolean containsRow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetRow().getMap().containsKey(key);
  }
  /**
   * Use {@link #getRowMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getRow() {
    return getRowMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; row = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getRowMap() {
    return internalGetRow().getMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; row = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
com.google.protobuf.ByteString getRowOrDefault(
      java.lang.String key,
      /* nullable */
com.google.protobuf.ByteString defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetRow().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bytes&gt; row = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRowOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetRow().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetRow(),
        RowDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
         : internalGetRow().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
      row__ = RowDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, row__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.dbsyncer.common.binlog.proto.BinlogMap)) {
      return super.equals(obj);
    }
    org.dbsyncer.common.binlog.proto.BinlogMap other = (org.dbsyncer.common.binlog.proto.BinlogMap) obj;

    if (!internalGetRow().equals(
        other.internalGetRow())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetRow().getMap().isEmpty()) {
      hash = (37 * hash) + ROW_FIELD_NUMBER;
      hash = (53 * hash) + internalGetRow().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.dbsyncer.common.binlog.proto.BinlogMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.dbsyncer.common.binlog.proto.BinlogMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.dbsyncer.common.binlog.proto.BinlogMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BinlogMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BinlogMap)
      org.dbsyncer.common.binlog.proto.BinlogMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dbsyncer.common.binlog.proto.BinlogMessageProto.internal_static_BinlogMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetRow();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableRow();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dbsyncer.common.binlog.proto.BinlogMessageProto.internal_static_BinlogMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.dbsyncer.common.binlog.proto.BinlogMap.class, org.dbsyncer.common.binlog.proto.BinlogMap.Builder.class);
    }

    // Construct using org.dbsyncer.common.binlog.proto.BinlogMap.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableRow().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.dbsyncer.common.binlog.proto.BinlogMessageProto.internal_static_BinlogMap_descriptor;
    }

    @java.lang.Override
    public org.dbsyncer.common.binlog.proto.BinlogMap getDefaultInstanceForType() {
      return org.dbsyncer.common.binlog.proto.BinlogMap.getDefaultInstance();
    }

    @java.lang.Override
    public org.dbsyncer.common.binlog.proto.BinlogMap build() {
      org.dbsyncer.common.binlog.proto.BinlogMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.dbsyncer.common.binlog.proto.BinlogMap buildPartial() {
      org.dbsyncer.common.binlog.proto.BinlogMap result = new org.dbsyncer.common.binlog.proto.BinlogMap(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.dbsyncer.common.binlog.proto.BinlogMap result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.row_ = internalGetRow();
        result.row_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.dbsyncer.common.binlog.proto.BinlogMap) {
        return mergeFrom((org.dbsyncer.common.binlog.proto.BinlogMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.dbsyncer.common.binlog.proto.BinlogMap other) {
      if (other == org.dbsyncer.common.binlog.proto.BinlogMap.getDefaultInstance()) return this;
      internalGetMutableRow().mergeFrom(
          other.internalGetRow());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
              row__ = input.readMessage(
                  RowDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableRow().getMutableMap().put(
                  row__.getKey(), row__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> row_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
        internalGetRow() {
      if (row_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RowDefaultEntryHolder.defaultEntry);
      }
      return row_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
        internalGetMutableRow() {
      if (row_ == null) {
        row_ = com.google.protobuf.MapField.newMapField(
            RowDefaultEntryHolder.defaultEntry);
      }
      if (!row_.isMutable()) {
        row_ = row_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return row_;
    }
    public int getRowCount() {
      return internalGetRow().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    @java.lang.Override
    public boolean containsRow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetRow().getMap().containsKey(key);
    }
    /**
     * Use {@link #getRowMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getRow() {
      return getRowMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getRowMap() {
      return internalGetRow().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.ByteString getRowOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetRow().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRowOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetRow().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearRow() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableRow().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    public Builder removeRow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableRow().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
        getMutableRow() {
      bitField0_ |= 0x00000001;
      return internalGetMutableRow().getMutableMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    public Builder putRow(
        java.lang.String key,
        com.google.protobuf.ByteString value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableRow().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; row = 1;</code>
     */
    public Builder putAllRow(
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
      internalGetMutableRow().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BinlogMap)
  }

  // @@protoc_insertion_point(class_scope:BinlogMap)
  private static final org.dbsyncer.common.binlog.proto.BinlogMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.dbsyncer.common.binlog.proto.BinlogMap();
  }

  public static org.dbsyncer.common.binlog.proto.BinlogMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BinlogMap>
      PARSER = new com.google.protobuf.AbstractParser<BinlogMap>() {
    @java.lang.Override
    public BinlogMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BinlogMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BinlogMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.dbsyncer.common.binlog.proto.BinlogMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

