DROP TABLE IF EXISTS ddlTestSource;
DROP TABLE IF EXISTS ddlTestTarget;
CREATE TABLE ddlTestSource (id INT AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50), department VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ddlTestTarget (id INT AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50), department VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

